num=1
try:
    print(num)
except NameError:

  print ("this is name error")
finally:
   

